export const SEED_TICKETS = [
  {
    id: 1,
    topic: 'Deleted user props returned in GET endpoint',
    summary: 'GET user properties API still returns properties that have been deleted. Known bug, not prioritised.',
    classification: 'Bug',
    fressnapf_status: 'Open',
    amplitude_status: 'Closed',
    zendesk_ticket_id: '372935',
    zendesk_url: 'https://help.amplitude.com/hc/en-us/requests/372935',
    productboard_note_id: '51713875',
    productboard_url: 'https://app.productboard.com/notes/51713875',
    productboard_status: 'Unprocessed',
    pm_owner: 'None',
    pillar: 'Governance',
    reporter: 'Florian Götting',
    created_date: '2024-11-15',
    last_updated: '2025-05-28T00:00:00Z',
    notes: 'Known bug confirmed by engineering. Not on current roadmap. AMP-148857 in backlog.',
    engineering_ref: 'AMP-148857',
  },
  {
    id: 2,
    topic: 'Nested array splitting not supported',
    summary: 'Taxonomy API does not support splitting nested arrays — product limitation.',
    classification: 'Product limitation',
    fressnapf_status: 'Open',
    amplitude_status: 'Closed',
    zendesk_ticket_id: '373624',
    zendesk_url: 'https://help.amplitude.com/hc/en-us/requests/373624',
    productboard_note_id: '51448847',
    productboard_url: 'https://app.productboard.com/notes/51448847',
    productboard_status: 'Unprocessed',
    pm_owner: 'None',
    pillar: 'Governance',
    reporter: 'Florian Götting',
    created_date: '2024-11-20',
    last_updated: '2025-05-28T00:00:00Z',
    notes: 'Fundamental architecture limitation. Would require significant rework of ingestion pipeline.',
    engineering_ref: null,
  },
  {
    id: 3,
    topic: 'Channel definitions API',
    summary: 'New API for channel definitions — shipped and resolved.',
    classification: 'FR',
    fressnapf_status: 'Fixed',
    amplitude_status: 'Resolved',
    zendesk_ticket_id: '383898',
    zendesk_url: 'https://help.amplitude.com/hc/en-us/requests/383898',
    productboard_note_id: '53211010',
    productboard_url: 'https://app.productboard.com/notes/53211010',
    productboard_status: 'Unprocessed',
    pm_owner: 'None',
    pillar: 'Governance',
    reporter: 'Florian Götting',
    created_date: '2025-02-10',
    last_updated: '2025-05-28T00:00:00Z',
    notes: 'Resolved. New API shipped Q1 2025.',
    engineering_ref: null,
  },
  {
    id: 4,
    topic: 'Array item type update via Taxonomy API',
    summary: 'Could not update array item types via Taxonomy API — fixed.',
    classification: 'Bug',
    fressnapf_status: 'Fixed',
    amplitude_status: 'Resolved',
    zendesk_ticket_id: '384416',
    zendesk_url: 'https://help.amplitude.com/hc/en-us/requests/384416',
    productboard_note_id: null,
    productboard_url: null,
    productboard_status: 'Not Logged',
    pm_owner: 'None',
    pillar: 'Governance',
    reporter: 'Florian Götting',
    created_date: '2025-02-15',
    last_updated: '2025-05-28T00:00:00Z',
    notes: 'Bug fix deployed. Confirmed working by Fressnapf.',
    engineering_ref: null,
  },
  {
    id: 5,
    topic: 'User property display name via Taxonomy API',
    summary: 'Cannot set display_name for user properties through the Taxonomy API.',
    classification: 'FR',
    fressnapf_status: 'Open',
    amplitude_status: 'Closed',
    zendesk_ticket_id: '384417',
    zendesk_url: 'https://help.amplitude.com/hc/en-us/requests/384417',
    productboard_note_id: '53390704',
    productboard_url: 'https://app.productboard.com/notes/53390704',
    productboard_status: 'Unprocessed',
    pm_owner: 'None',
    pillar: 'Governance',
    reporter: 'Florian Götting',
    created_date: '2025-02-15',
    last_updated: '2025-05-28T00:00:00Z',
    notes: 'Feature request logged but unprocessed. No PM assigned.',
    engineering_ref: null,
  },
  {
    id: 6,
    topic: 'OOTB metric UI editing',
    summary: 'Out-of-the-box metrics could not be edited in UI — fixed.',
    classification: 'Bug',
    fressnapf_status: 'Fixed',
    amplitude_status: 'Resolved',
    zendesk_ticket_id: '384634',
    zendesk_url: 'https://help.amplitude.com/hc/en-us/requests/384634',
    productboard_note_id: null,
    productboard_url: null,
    productboard_status: 'Not Logged',
    pm_owner: 'None',
    pillar: 'Analytics',
    reporter: 'Kateryna Osypova',
    created_date: '2025-02-18',
    last_updated: '2025-05-28T00:00:00Z',
    notes: 'UI fix deployed.',
    engineering_ref: null,
  },
  {
    id: 7,
    topic: 'Event display_name API',
    summary: 'GET event type API was not returning the display_name field — fixed.',
    classification: 'Bug',
    fressnapf_status: 'Fixed',
    amplitude_status: 'Resolved',
    zendesk_ticket_id: '386375',
    zendesk_url: 'https://help.amplitude.com/hc/en-us/requests/386375',
    productboard_note_id: '53763405',
    productboard_url: 'https://app.productboard.com/notes/53763405',
    productboard_status: 'Unprocessed',
    pm_owner: 'None',
    pillar: 'Governance',
    reporter: 'Florian Götting',
    created_date: '2025-03-01',
    last_updated: '2025-05-28T00:00:00Z',
    notes: 'Fixed. display_name field now returned in API response.',
    engineering_ref: null,
  },
  {
    id: 8,
    topic: 'Copy channel definitions across projects',
    summary: 'No way to copy channel definitions from one project to another. FR + bug in existing copy functionality.',
    classification: 'FR',
    fressnapf_status: 'Open',
    amplitude_status: 'Closed',
    zendesk_ticket_id: '384929',
    zendesk_url: 'https://help.amplitude.com/hc/en-us/requests/384929',
    productboard_note_id: '54042671',
    productboard_url: 'https://app.productboard.com/notes/54042671',
    productboard_status: 'Unprocessed',
    pm_owner: 'None',
    pillar: 'Governance',
    reporter: 'Florian Götting',
    created_date: '2025-02-20',
    last_updated: '2025-05-28T00:00:00Z',
    notes: 'Logged as FR. Existing project copy does not include channel definitions.',
    engineering_ref: null,
  },
  {
    id: 9,
    topic: 'OOTB metrics share one Page View definition',
    summary: 'All out-of-the-box metrics reference a single Page View event definition. Architectural issue prevents per-metric customisation.',
    classification: 'Product limitation',
    fressnapf_status: 'Open',
    amplitude_status: 'On Hold',
    zendesk_ticket_id: '388840',
    zendesk_url: 'https://help.amplitude.com/hc/en-us/requests/388840',
    productboard_note_id: null,
    productboard_url: null,
    productboard_status: 'Not Logged',
    pm_owner: 'None',
    pillar: 'Analytics',
    reporter: 'Kateryna Osypova',
    created_date: '2025-03-15',
    last_updated: '2025-05-28T00:00:00Z',
    notes: 'Architectural constraint. Engineering aware but no planned fix. Not logged in Productboard.',
    engineering_ref: 'AMP-150769',
  },
  {
    id: 10,
    topic: 'Session Replay Agent not finding sessions',
    summary: 'Session Replay AI agent was not surfacing relevant sessions — fixed.',
    classification: 'Bug',
    fressnapf_status: 'Fixed',
    amplitude_status: 'Resolved',
    zendesk_ticket_id: '390732',
    zendesk_url: 'https://help.amplitude.com/hc/en-us/requests/390732',
    productboard_note_id: '51399705',
    productboard_url: 'https://app.productboard.com/notes/51399705',
    productboard_status: 'Unprocessed',
    pm_owner: 'None',
    pillar: 'Analytics',
    reporter: 'Sebastian Damm',
    created_date: '2025-04-01',
    last_updated: '2025-05-28T00:00:00Z',
    notes: 'Fixed. Note: PB note 51399705 is for overrideScope in create event property, a related but separate issue.',
    engineering_ref: null,
  },
  {
    id: 11,
    topic: 'Dynamic Sampling cannot be disabled',
    summary: 'Dynamic sampling toggle was not working — fixed.',
    classification: 'Bug',
    fressnapf_status: 'Fixed',
    amplitude_status: 'Resolved',
    zendesk_ticket_id: '391041',
    zendesk_url: 'https://help.amplitude.com/hc/en-us/requests/391041',
    productboard_note_id: null,
    productboard_url: null,
    productboard_status: 'Not Logged',
    pm_owner: 'None',
    pillar: 'Data Management',
    reporter: 'Sebastian Damm',
    created_date: '2025-04-05',
    last_updated: '2025-05-28T00:00:00Z',
    notes: 'Bug fix deployed. Sampling can now be disabled.',
    engineering_ref: null,
  },
  {
    id: 12,
    topic: 'Lookup Table 1M cumulative row limit',
    summary: 'Lookup tables have a 1M cumulative row limit across all tables. Fressnapf hitting this limit.',
    classification: 'Product limitation',
    fressnapf_status: 'Open',
    amplitude_status: 'Closed',
    zendesk_ticket_id: '391631',
    zendesk_url: 'https://help.amplitude.com/hc/en-us/requests/391631',
    productboard_note_id: null,
    productboard_url: null,
    productboard_status: 'Not Logged',
    pm_owner: 'None',
    pillar: 'Data Management',
    reporter: 'Florian Götting',
    created_date: '2025-04-10',
    last_updated: '2025-05-28T00:00:00Z',
    notes: 'Product limitation. Generic FR exists from Amazon, Dell, HEB, Mercado Libre, Fandom, Moderna — but no Fressnapf-specific note in PB.',
    engineering_ref: 'AMP-149510',
  },
  {
    id: 13,
    topic: 'Configurable reset/unset value for campaign props',
    summary: 'Campaign properties cannot be reset or unset with a configurable value.',
    classification: 'FR',
    fressnapf_status: 'Open',
    amplitude_status: 'Closed',
    zendesk_ticket_id: '392406',
    zendesk_url: 'https://help.amplitude.com/hc/en-us/requests/392406',
    productboard_note_id: '55406553',
    productboard_url: 'https://app.productboard.com/notes/55406553',
    productboard_status: 'Unprocessed',
    pm_owner: 'None',
    pillar: 'Governance',
    reporter: 'Markus Buss',
    created_date: '2025-04-18',
    last_updated: '2025-05-28T00:00:00Z',
    notes: 'FR logged. No PM owner assigned.',
    engineering_ref: null,
  },
  {
    id: 14,
    topic: 'EU endpoint outage',
    summary: 'EU data endpoint experienced outage — resolved.',
    classification: 'Bug',
    fressnapf_status: 'Fixed',
    amplitude_status: 'Resolved',
    zendesk_ticket_id: '392786',
    zendesk_url: 'https://help.amplitude.com/hc/en-us/requests/392786',
    productboard_note_id: null,
    productboard_url: null,
    productboard_status: 'Not Logged',
    pm_owner: 'None',
    pillar: 'Data Management',
    reporter: 'Sebastian Damm',
    created_date: '2025-04-22',
    last_updated: '2025-05-28T00:00:00Z',
    notes: 'Infrastructure incident resolved.',
    engineering_ref: null,
  },
  {
    id: 15,
    topic: 'Custom Event rename breaks existing charts',
    summary: 'Renaming a custom event does not propagate to existing charts that reference it.',
    classification: 'FR',
    fressnapf_status: 'Open',
    amplitude_status: 'Closed',
    zendesk_ticket_id: '384657',
    zendesk_url: 'https://help.amplitude.com/hc/en-us/requests/384657',
    productboard_note_id: '53417952',
    productboard_url: 'https://app.productboard.com/notes/53417952',
    productboard_status: 'Unprocessed',
    pm_owner: 'None',
    pillar: 'Analytics',
    reporter: 'Kateryna Osypova',
    created_date: '2025-02-19',
    last_updated: '2025-05-28T00:00:00Z',
    notes: 'Charts still reference old event name after rename. Would need rename propagation logic.',
    engineering_ref: 'AMP-148774',
  },
  {
    id: 16,
    topic: 'Percentage point change in time comparisons',
    summary: 'Time comparison charts show percentage change instead of percentage point change.',
    classification: 'FR',
    fressnapf_status: 'Open',
    amplitude_status: 'Closed',
    zendesk_ticket_id: '385281',
    zendesk_url: 'https://help.amplitude.com/hc/en-us/requests/385281',
    productboard_note_id: '53697967',
    productboard_url: 'https://app.productboard.com/notes/53697967',
    productboard_status: 'Unprocessed',
    pm_owner: 'None',
    pillar: 'Analytics',
    reporter: 'Kateryna Osypova',
    created_date: '2025-02-25',
    last_updated: '2025-05-28T00:00:00Z',
    notes: 'UX issue in chart comparisons. FR logged but not processed.',
    engineering_ref: null,
  },
  {
    id: 17,
    topic: 'Expire Persisted Properties after specific event',
    summary: 'No mechanism to expire persisted properties after a specific event fires.',
    classification: 'FR',
    fressnapf_status: 'Open',
    amplitude_status: 'Closed',
    zendesk_ticket_id: '389995',
    zendesk_url: 'https://help.amplitude.com/hc/en-us/requests/389995',
    productboard_note_id: '54240981',
    productboard_url: 'https://app.productboard.com/notes/54240981',
    productboard_status: 'Unprocessed',
    pm_owner: 'None',
    pillar: 'Analytics',
    reporter: 'Markus Buss',
    created_date: '2025-03-20',
    last_updated: '2025-05-28T00:00:00Z',
    notes: 'Would require new property lifecycle management feature.',
    engineering_ref: null,
  },
  {
    id: 18,
    topic: 'Array splitting / project switching bug',
    summary: 'Array splitting configuration gets lost or behaves inconsistently when switching between projects.',
    classification: 'Bug',
    fressnapf_status: 'Open',
    amplitude_status: 'On Hold',
    zendesk_ticket_id: '392950',
    zendesk_url: 'https://help.amplitude.com/hc/en-us/requests/392950',
    productboard_note_id: null,
    productboard_url: null,
    productboard_status: 'Not Logged',
    pm_owner: 'None',
    pillar: 'Analytics',
    reporter: 'Florian Götting',
    created_date: '2025-04-25',
    last_updated: '2025-05-28T00:00:00Z',
    notes: 'Active bug. Engineering investigating. On hold pending fix.',
    engineering_ref: 'AMP-141321',
  },
  {
    id: 19,
    topic: 'Event properties in user-based visualisations',
    summary: 'Event properties cannot be used in user-based chart visualisations (e.g. user composition).',
    classification: 'FR',
    fressnapf_status: 'Open',
    amplitude_status: 'Closed',
    zendesk_ticket_id: '393788',
    zendesk_url: 'https://help.amplitude.com/hc/en-us/requests/393788',
    productboard_note_id: null,
    productboard_url: null,
    productboard_status: 'Not Logged',
    pm_owner: 'None',
    pillar: 'Analytics',
    reporter: 'Sebastian Damm',
    created_date: '2025-05-01',
    last_updated: '2025-05-28T00:00:00Z',
    notes: 'Architectural limitation. Event properties are event-scoped and cannot be projected to user-level aggregations without explicit mapping.',
    engineering_ref: null,
  },
  {
    id: 20,
    topic: 'Data Table labels wrong and non-editable',
    summary: 'Data Table chart type shows incorrect labels and they cannot be edited.',
    classification: 'Bug',
    fressnapf_status: 'Open',
    amplitude_status: 'Open',
    zendesk_ticket_id: '394661',
    zendesk_url: 'https://help.amplitude.com/hc/en-us/requests/394661',
    productboard_note_id: null,
    productboard_url: null,
    productboard_status: 'Not Logged',
    pm_owner: 'None',
    pillar: 'Analytics',
    reporter: 'Kateryna Osypova',
    created_date: '2025-05-15',
    last_updated: '2025-05-28T00:00:00Z',
    notes: 'Active ticket. CAP-388 logged in Linear.',
    engineering_ref: 'CAP-388',
  },
]
