export const SEED_TICKETS = [
  {
    id: 1,
    topic: 'Deleted user props returned in GET endpoint',
    summary: 'GET user properties API still returns properties that have been deleted. Known bug, not prioritised.',
    classification: 'Bug',
    fressnapf_status: 'Open',
    amplitude_status: 'Closed',
    zendesk_ticket_id: '372935',
    zendesk_url: 'https://gethelp.amplitude.com/hc/requests/372935',
    productboard_note_id: '51713875',
    productboard_url: 'https://app.productboard.com/notes/51713875',
    productboard_status: 'Unprocessed',
    pm_owner: 'None',
    pillar: 'Governance',
    reporter: 'Florian Götting',
    created_date: '2024-11-15',
    last_updated: '2025-05-28T00:00:00Z',
    notes: 'Known bug confirmed by engineering. Not on current roadmap. AMP-148857 in backlog.',
    engineering_ref: 'AMP-148857',
  },
  {
    id: 2,
    topic: 'Nested array splitting not supported',
    summary: 'Taxonomy API does not support splitting nested arrays — product limitation.',
    classification: 'Product limitation',
    fressnapf_status: 'Open',
    amplitude_status: 'Closed',
    zendesk_ticket_id: '373624',
    zendesk_url: 'https://gethelp.amplitude.com/hc/requests/373624',
    productboard_note_id: '51448847',
    productboard_url: 'https://app.productboard.com/notes/51448847',
    productboard_status: 'Unprocessed',
    pm_owner: 'None',
    pillar: 'Governance',
    reporter: 'Florian Götting',
    created_date: '2024-11-20',
    last_updated: '2025-05-28T00:00:00Z',
    notes: 'Fundamental architecture limitation. Would require significant rework of ingestion pipeline.',
    engineering_ref: null,
  },
  {
    id: 3,
    topic: 'User property display name via Taxonomy API',
    summary: 'Cannot set display_name for user properties through the Taxonomy API.',
    classification: 'FR',
    fressnapf_status: 'Open',
    amplitude_status: 'Closed',
    zendesk_ticket_id: '384417',
    zendesk_url: 'https://gethelp.amplitude.com/hc/requests/384417',
    productboard_note_id: '53390704',
    productboard_url: 'https://app.productboard.com/notes/53390704',
    productboard_status: 'Unprocessed',
    pm_owner: 'None',
    pillar: 'Governance',
    reporter: 'Florian Götting',
    created_date: '2025-02-15',
    last_updated: '2025-05-28T00:00:00Z',
    notes: 'Feature request logged but unprocessed. No PM assigned.',
    engineering_ref: null,
  },
  {
    id: 4,
    topic: 'Copy channel definitions across projects',
    summary: 'No way to copy channel definitions from one project to another. FR + bug in existing copy functionality.',
    classification: 'FR',
    fressnapf_status: 'Open',
    amplitude_status: 'Closed',
    zendesk_ticket_id: '384929',
    zendesk_url: 'https://gethelp.amplitude.com/hc/requests/384929',
    productboard_note_id: '54042671',
    productboard_url: 'https://app.productboard.com/notes/54042671',
    productboard_status: 'Unprocessed',
    pm_owner: 'None',
    pillar: 'Governance',
    reporter: 'Florian Götting',
    created_date: '2025-02-20',
    last_updated: '2025-05-28T00:00:00Z',
    notes: 'Logged as FR. Existing project copy does not include channel definitions.',
    engineering_ref: null,
  },
  {
    id: 5,
    topic: 'OOTB metrics share one Page View definition',
    summary: 'All out-of-the-box metrics reference a single Page View event definition. Architectural issue prevents per-metric customisation.',
    classification: 'Product limitation',
    fressnapf_status: 'Open',
    amplitude_status: 'On Hold',
    zendesk_ticket_id: '388840',
    zendesk_url: 'https://gethelp.amplitude.com/hc/requests/388840',
    productboard_note_id: null,
    productboard_url: null,
    productboard_status: 'Not Logged',
    pm_owner: 'None',
    pillar: 'Analytics',
    reporter: 'Kateryna Osypova',
    created_date: '2025-03-15',
    last_updated: '2025-05-28T00:00:00Z',
    notes: 'Architectural constraint. Engineering aware but no planned fix. Not logged in Productboard.',
    engineering_ref: 'AMP-150769',
  },
  {
    id: 6,
    topic: 'Lookup Table 1M cumulative row limit',
    summary: 'Lookup tables have a 1M cumulative row limit across all tables. Fressnapf hitting this limit.',
    classification: 'Product limitation',
    fressnapf_status: 'Open',
    amplitude_status: 'Closed',
    zendesk_ticket_id: '391631',
    zendesk_url: 'https://gethelp.amplitude.com/hc/requests/391631',
    productboard_note_id: null,
    productboard_url: null,
    productboard_status: 'Not Logged',
    pm_owner: 'None',
    pillar: 'Data Management',
    reporter: 'Florian Götting',
    created_date: '2025-04-10',
    last_updated: '2025-05-28T00:00:00Z',
    notes: 'Product limitation. Generic FR exists from Amazon, Dell, HEB, Mercado Libre, Fandom, Moderna — but no Fressnapf-specific note in PB.',
    engineering_ref: 'AMP-149510',
  },
  {
    id: 7,
    topic: 'Configurable reset/unset value for campaign props',
    summary: 'Campaign properties cannot be reset or unset with a configurable value.',
    classification: 'FR',
    fressnapf_status: 'Open',
    amplitude_status: 'Closed',
    zendesk_ticket_id: '392406',
    zendesk_url: 'https://gethelp.amplitude.com/hc/requests/392406',
    productboard_note_id: '55406553',
    productboard_url: 'https://app.productboard.com/notes/55406553',
    productboard_status: 'Unprocessed',
    pm_owner: 'None',
    pillar: 'Governance',
    reporter: 'Markus Buss',
    created_date: '2025-04-18',
    last_updated: '2025-05-28T00:00:00Z',
    notes: 'FR logged. No PM owner assigned.',
    engineering_ref: null,
  },
  {
    id: 8,
    topic: 'Custom Event rename breaks existing charts',
    summary: 'Renaming a custom event does not propagate to existing charts that reference it.',
    classification: 'FR',
    fressnapf_status: 'Open',
    amplitude_status: 'Closed',
    zendesk_ticket_id: '384657',
    zendesk_url: 'https://gethelp.amplitude.com/hc/requests/384657',
    productboard_note_id: '53417952',
    productboard_url: 'https://app.productboard.com/notes/53417952',
    productboard_status: 'Unprocessed',
    pm_owner: 'None',
    pillar: 'Analytics',
    reporter: 'Kateryna Osypova',
    created_date: '2025-02-19',
    last_updated: '2025-05-28T00:00:00Z',
    notes: 'Charts still reference old event name after rename. Would need rename propagation logic.',
    engineering_ref: 'AMP-148774',
  },
  {
    id: 9,
    topic: 'Percentage point change in time comparisons',
    summary: 'Time comparison charts show percentage change instead of percentage point change.',
    classification: 'FR',
    fressnapf_status: 'Open',
    amplitude_status: 'Closed',
    zendesk_ticket_id: '385281',
    zendesk_url: 'https://gethelp.amplitude.com/hc/requests/385281',
    productboard_note_id: '53697967',
    productboard_url: 'https://app.productboard.com/notes/53697967',
    productboard_status: 'Unprocessed',
    pm_owner: 'None',
    pillar: 'Analytics',
    reporter: 'Kateryna Osypova',
    created_date: '2025-02-25',
    last_updated: '2025-05-28T00:00:00Z',
    notes: 'UX issue in chart comparisons. FR logged but not processed.',
    engineering_ref: null,
  },
  {
    id: 10,
    topic: 'Expire Persisted Properties after specific event',
    summary: 'No mechanism to expire persisted properties after a specific event fires.',
    classification: 'FR',
    fressnapf_status: 'Open',
    amplitude_status: 'Closed',
    zendesk_ticket_id: '389995',
    zendesk_url: 'https://gethelp.amplitude.com/hc/requests/389995',
    productboard_note_id: '54240981',
    productboard_url: 'https://app.productboard.com/notes/54240981',
    productboard_status: 'Unprocessed',
    pm_owner: 'None',
    pillar: 'Analytics',
    reporter: 'Markus Buss',
    created_date: '2025-03-20',
    last_updated: '2025-05-28T00:00:00Z',
    notes: 'Would require new property lifecycle management feature.',
    engineering_ref: null,
  },
  {
    id: 11,
    topic: 'Array splitting / project switching bug',
    summary: 'Array splitting configuration gets lost or behaves inconsistently when switching between projects.',
    classification: 'Bug',
    fressnapf_status: 'Open',
    amplitude_status: 'On Hold',
    zendesk_ticket_id: '392950',
    zendesk_url: 'https://gethelp.amplitude.com/hc/requests/392950',
    productboard_note_id: null,
    productboard_url: null,
    productboard_status: 'Not Logged',
    pm_owner: 'None',
    pillar: 'Analytics',
    reporter: 'Florian Götting',
    created_date: '2025-04-25',
    last_updated: '2025-05-28T00:00:00Z',
    notes: 'Active bug. Engineering investigating. On hold pending fix.',
    engineering_ref: 'AMP-141321',
  },
  {
    id: 12,
    topic: 'Event properties in user-based visualisations',
    summary: 'Event properties cannot be used in user-based chart visualisations (e.g. user composition).',
    classification: 'FR',
    fressnapf_status: 'Open',
    amplitude_status: 'Closed',
    zendesk_ticket_id: '393788',
    zendesk_url: 'https://gethelp.amplitude.com/hc/en-us/requests/393788',
    productboard_note_id: null,
    productboard_url: null,
    productboard_status: 'Not Logged',
    pm_owner: 'None',
    pillar: 'Analytics',
    reporter: 'Sebastian Damm',
    created_date: '2025-05-01',
    last_updated: '2025-05-28T00:00:00Z',
    notes: 'Architectural limitation. Event properties are event-scoped and cannot be projected to user-level aggregations without explicit mapping.',
    engineering_ref: null,
  },
]
