// Offline fallback shown only if the API is unreachable. Kept in sync with the
// server seed in api/seed.js — the consolidated Fressnapf FR & bug list
// ("Fressnapf_Requests_and_Bugs", 09 Jul 2026). Part 1 = FRs, Part 2 = Bugs.
const zd = (id) => `https://amplitude.zendesk.com/agent/tickets/${id}`

export const SEED_TICKETS = [
  // --- Part 1: Feature Requests ---
  {
    id: 1,
    topic: 'Count Items & Count Events on Data Table Total Counts',
    summary: 'When grouping by cart properties, let Event Totals offer both selectable measures (like Segmentation) for order-level vs item-level analysis.',
    classification: 'FR',
    fressnapf_status: 'Open',
    amplitude_status: 'In Engineering',
    zendesk_ticket_id: null,
    zendesk_url: null,
    productboard_note_id: null,
    productboard_url: null,
    productboard_status: 'Not Logged',
    pm_owner: 'None',
    pillar: 'Analytics',
    reporter: 'Liping Yin (for Kateryna Osypova)',
    created_date: '2026-07-09',
    last_updated: '2026-07-09T00:00:00Z',
    notes: 'Channel: #pillar-analytics (Submit Pillar Feedback). FE concept built (Dan Carmel); wiring in progress (Brian Cooper); Liping confirming with customer.',
    engineering_ref: 'QRY-550',
  },
  {
    id: 2,
    topic: 'Copy channel classifiers / definitions across projects',
    summary: 'Copy channel classifiers / definitions across projects to avoid manual recreation.',
    classification: 'FR',
    fressnapf_status: 'Open',
    amplitude_status: 'On Hold',
    zendesk_ticket_id: null,
    zendesk_url: null,
    productboard_note_id: null,
    productboard_url: null,
    productboard_status: 'Not Logged',
    pm_owner: 'None',
    pillar: 'Analytics',
    reporter: 'Liping Yin',
    created_date: '2026-07-09',
    last_updated: '2026-07-09T00:00:00Z',
    notes: 'Channel: #marketing-analytics. Previously existed, then disabled; workaround = copy rows.',
    engineering_ref: 'AMP-65915',
  },
  {
    id: 3,
    topic: 'Data Assistant Agent: rollback + cross-project taxonomy sync',
    summary: 'Data Assistant Agent rollback plus cross-project taxonomy sync (master to country propagation).',
    classification: 'FR',
    fressnapf_status: 'Open',
    amplitude_status: 'On Hold',
    zendesk_ticket_id: '400111',
    zendesk_url: zd('400111'),
    productboard_note_id: null,
    productboard_url: null,
    productboard_status: 'Not Logged',
    pm_owner: 'None',
    pillar: 'Data Management',
    reporter: 'Liping Yin',
    created_date: '2026-07-09',
    last_updated: '2026-07-09T00:00:00Z',
    notes: 'Channel: #pillar-agents. Not supported today; folded into cross-project propagation planning.',
    engineering_ref: null,
  },
  {
    id: 4,
    topic: 'Enable array (cart) splitting via Taxonomy API',
    summary: 'Enable array (cart) splitting via the Taxonomy API — currently UI-only after is_array_type=true.',
    classification: 'FR',
    fressnapf_status: 'Open',
    amplitude_status: 'Unprocessed',
    zendesk_ticket_id: '372093',
    zendesk_url: zd('372093'),
    productboard_note_id: null,
    productboard_url: null,
    productboard_status: 'Unprocessed',
    pm_owner: 'None',
    pillar: 'Governance',
    reporter: 'Florian Götting / Liping Yin',
    created_date: '2026-07-09',
    last_updated: '2026-07-09T00:00:00Z',
    notes: 'Channel: #product-feedback. Logged as a Productboard note.',
    engineering_ref: null,
  },
  {
    id: 5,
    topic: 'API to get/set channel information for multi-project automation',
    summary: 'API to retrieve and set channel information for multi-project automation.',
    classification: 'FR',
    fressnapf_status: 'Open',
    amplitude_status: 'Unprocessed',
    zendesk_ticket_id: '383898',
    zendesk_url: zd('383898'),
    productboard_note_id: null,
    productboard_url: null,
    productboard_status: 'Unprocessed',
    pm_owner: 'None',
    pillar: 'Governance',
    reporter: 'Florian Götting / Liping Yin',
    created_date: '2026-07-09',
    last_updated: '2026-07-09T00:00:00Z',
    notes: 'Channel: #product-feedback. Logged as a Productboard note.',
    engineering_ref: null,
  },
  {
    id: 6,
    topic: 'overrideScope="shared" option on create-event-property endpoint',
    summary: 'Add an overrideScope="shared" option to the create-event-property endpoint to avoid auto-overrides.',
    classification: 'FR',
    fressnapf_status: 'Open',
    amplitude_status: 'Unprocessed',
    zendesk_ticket_id: '372883',
    zendesk_url: zd('372883'),
    productboard_note_id: null,
    productboard_url: null,
    productboard_status: 'Unprocessed',
    pm_owner: 'None',
    pillar: 'Governance',
    reporter: 'Florian Götting / Liping Yin',
    created_date: '2026-07-09',
    last_updated: '2026-07-09T00:00:00Z',
    notes: 'Channel: #product-feedback. Logged as a Productboard note.',
    engineering_ref: null,
  },
  {
    id: 7,
    topic: 'User-properties API returns deleted properties',
    summary: 'Fix inconsistency in the user-properties API — stop returning deleted properties (align with the event-properties endpoint).',
    classification: 'FR',
    fressnapf_status: 'Open',
    amplitude_status: 'Unprocessed',
    zendesk_ticket_id: '372935',
    zendesk_url: zd('372935'),
    productboard_note_id: null,
    productboard_url: null,
    productboard_status: 'Unprocessed',
    pm_owner: 'None',
    pillar: 'Governance',
    reporter: 'Florian Götting / Jake Lee',
    created_date: '2026-07-09',
    last_updated: '2026-07-09T00:00:00Z',
    notes: 'Channel: #product-feedback. Logged as a Productboard note. Also historically tracked as a bug under ZD 372935.',
    engineering_ref: null,
  },
  {
    id: 8,
    topic: 'Persisted-property expiration by event',
    summary: 'Persisted-property expiration by event (e.g. expire after backend_order), not just visit/time-based.',
    classification: 'FR',
    fressnapf_status: 'Open',
    amplitude_status: 'Unprocessed',
    zendesk_ticket_id: null,
    zendesk_url: null,
    productboard_note_id: null,
    productboard_url: null,
    productboard_status: 'Not Logged',
    pm_owner: 'None',
    pillar: 'Analytics',
    reporter: 'Giuliano Giannini',
    created_date: '2026-07-09',
    last_updated: '2026-07-09T00:00:00Z',
    notes: 'Channel: #analytics-persisted-properties-merchandising. Added to feedback list; raised multiple times pre-GA.',
    engineering_ref: null,
  },
  {
    id: 9,
    topic: 'Show complete / non-pruned results toggle in Data Tables',
    summary: 'A "show complete / non-pruned results" toggle in Data Tables for business-critical analysis.',
    classification: 'FR',
    fressnapf_status: 'Open',
    amplitude_status: 'On Hold',
    zendesk_ticket_id: null,
    zendesk_url: null,
    productboard_note_id: null,
    productboard_url: null,
    productboard_status: 'Not Logged',
    pm_owner: 'None',
    pillar: 'Analytics',
    reporter: 'Thao Nguyen (on behalf of customer)',
    created_date: '2026-07-09',
    last_updated: '2026-07-09T00:00:00Z',
    notes: 'Channel: #pillar-marketer-analytics. Higher-capacity mode discussed; unlimited toggle not planned.',
    engineering_ref: null,
  },
  {
    id: 10,
    topic: 'Funnel support for excluding bounced users',
    summary: 'Funnel support for excluding bounced users (Adobe "non-single page visit" equivalent).',
    classification: 'FR',
    fressnapf_status: 'Open',
    amplitude_status: 'Unprocessed',
    zendesk_ticket_id: null,
    zendesk_url: null,
    productboard_note_id: null,
    productboard_url: null,
    productboard_status: 'Not Logged',
    pm_owner: 'None',
    pillar: 'Analytics',
    reporter: 'Giuliano Giannini',
    created_date: '2026-07-09',
    last_updated: '2026-07-09T00:00:00Z',
    notes: 'Channel: #pillar-analytics. Raised as a question; borderline FR, no native support today.',
    engineering_ref: null,
  },
  {
    id: 11,
    topic: 'Filter dropdown should show "Direct" for renamed (none) persisted properties',
    summary: 'Filter dropdown should respect "Rename (none) -> Direct" for persisted properties — show "Direct" (not "(none)") in the filter value list so stakeholders can find it without knowing the underlying mapping.',
    classification: 'FR',
    fressnapf_status: 'Open',
    amplitude_status: 'In Engineering',
    zendesk_ticket_id: '400900',
    zendesk_url: zd('400900'),
    productboard_note_id: null,
    productboard_url: null,
    productboard_status: 'Unprocessed',
    pm_owner: 'None',
    pillar: 'Analytics',
    reporter: 'Liping Yin (for Sebastian Damm)',
    created_date: '2026-07-09',
    last_updated: '2026-07-09T00:00:00Z',
    notes: 'Channel: #pillar-analytics (Submit Pillar Feedback). Logged; tagged Core Analytics pod (Nive Suresh); customer added follow-up detail 7 Jul.',
    engineering_ref: null,
  },
  // --- Part 2: Bugs ---
  {
    id: 12,
    topic: 'Session Totals != Event Totals for order_created by persisted Channel',
    summary: 'Session Totals do not equal Event Totals for the same order_created grouped by persisted Channel (Direct off by ~14k, validated vs warehouse).',
    classification: 'Bug',
    fressnapf_status: 'Open',
    amplitude_status: 'In Engineering',
    zendesk_ticket_id: null,
    zendesk_url: null,
    productboard_note_id: null,
    productboard_url: null,
    productboard_status: 'Not Logged',
    pm_owner: 'None',
    pillar: 'Analytics',
    reporter: '',
    created_date: '2026-07-09',
    last_updated: '2026-07-09T00:00:00Z',
    notes: 'Channel: #analytics-persisted-properties-merchandising. Root cause: stale cache not invalidated; fix in review.',
    engineering_ref: 'MAR-211',
  },
  {
    id: 13,
    topic: 'Drilldown percentages do not reconcile across metric columns',
    summary: 'Drilldown percentages do not reconcile across metric columns (sums >100%, cross-metric inconsistency).',
    classification: 'Bug',
    fressnapf_status: 'Open',
    amplitude_status: 'On Hold',
    zendesk_ticket_id: null,
    zendesk_url: null,
    productboard_note_id: null,
    productboard_url: null,
    productboard_status: 'Not Logged',
    pm_owner: 'None',
    pillar: 'Analytics',
    reporter: '',
    created_date: '2026-07-09',
    last_updated: '2026-07-09T00:00:00Z',
    notes: 'Channel: #analytics-persisted-properties-merchandising. Largely assessed as expected; chart link disputed.',
    engineering_ref: 'MAR-212',
  },
  {
    id: 14,
    topic: 'Rows disappear when metric set changes (silent data loss)',
    summary: 'Rows disappear when the metric set changes — silent data loss (Share under "mai" vanishes).',
    classification: 'Bug',
    fressnapf_status: 'Open',
    amplitude_status: 'In Engineering',
    zendesk_ticket_id: null,
    zendesk_url: null,
    productboard_note_id: null,
    productboard_url: null,
    productboard_status: 'Not Logged',
    pm_owner: 'None',
    pillar: 'Analytics',
    reporter: '',
    created_date: '2026-07-09',
    last_updated: '2026-07-09T00:00:00Z',
    notes: 'Channel: #analytics-persisted-properties-merchandising. Confirmed bug (null value label); PR raised.',
    engineering_ref: 'MAR-213 / MIW-200',
  },
  {
    id: 15,
    topic: 'Changing one column metric impacts another column in Data Table',
    summary: 'Changing the metric of one column impacts the results of another column in a Data Table.',
    classification: 'Bug',
    fressnapf_status: 'Open',
    amplitude_status: 'In Engineering',
    zendesk_ticket_id: null,
    zendesk_url: null,
    productboard_note_id: null,
    productboard_url: null,
    productboard_status: 'Not Logged',
    pm_owner: 'None',
    pillar: 'Analytics',
    reporter: '',
    created_date: '2026-07-09',
    last_updated: '2026-07-09T00:00:00Z',
    notes: 'Channel: #pillar-marketer-analytics. Escalated red; repro difficulty (EU access).',
    engineering_ref: 'CAP-440 / MIW-337',
  },
  {
    id: 16,
    topic: 'Total Events vs Total Sessions group-by Cart properties discrepancy',
    summary: 'Total Events vs Total Sessions group-by Cart properties discrepancy.',
    classification: 'Bug',
    fressnapf_status: 'Open',
    amplitude_status: 'In Engineering',
    zendesk_ticket_id: null,
    zendesk_url: null,
    productboard_note_id: null,
    productboard_url: null,
    productboard_status: 'Not Logged',
    pm_owner: 'None',
    pillar: 'Analytics',
    reporter: '',
    created_date: '2026-07-09',
    last_updated: '2026-07-09T00:00:00Z',
    notes: 'Channel: #pillar-marketer-analytics. Escalated red; possibly linked to MIW-236.',
    engineering_ref: 'CAP-448 / QRY-550',
  },
  {
    id: 17,
    topic: '(other) row inflates / breaks split with Platform segmentation on PP table',
    summary: 'The (other) row inflates / breaks the split when Platform (web/app) segmentation is added to an event-based persisted-property table; refresh no longer fixes it.',
    classification: 'Bug',
    fressnapf_status: 'Fixed',
    amplitude_status: 'Closed',
    zendesk_ticket_id: null,
    zendesk_url: null,
    productboard_note_id: null,
    productboard_url: null,
    productboard_status: 'Not Logged',
    pm_owner: 'None',
    pillar: 'Analytics',
    reporter: '',
    created_date: '2026-07-09',
    last_updated: '2026-07-09T00:00:00Z',
    notes: 'Channel: #analytics-persisted-properties-merchandising. Root-caused to aggressive nested group-by pruning; quick fix deployed.',
    engineering_ref: 'CAP-396',
  },
  {
    id: 18,
    topic: 'Persisted event-property results do not match user-based for large countries',
    summary: 'Persisted event-property results do not match user-based results for large countries/global; tables disappear on project switch.',
    classification: 'Bug',
    fressnapf_status: 'Open',
    amplitude_status: 'In Engineering',
    zendesk_ticket_id: null,
    zendesk_url: null,
    productboard_note_id: null,
    productboard_url: null,
    productboard_status: 'Not Logged',
    pm_owner: 'None',
    pillar: 'Analytics',
    reporter: '',
    created_date: '2026-07-09',
    last_updated: '2026-07-09T00:00:00Z',
    notes: 'Channel: #analytics-persisted-properties-merchandising. Logged; low-results issue confirmed still reproducing.',
    engineering_ref: 'CAB-744',
  },
  {
    id: 19,
    topic: 'Dashboards take up to 10 min to load (persisted + derived props)',
    summary: 'Dashboards take up to 10 minutes to load (persisted + derived props + group-by).',
    classification: 'Bug',
    fressnapf_status: 'Open',
    amplitude_status: 'In Engineering',
    zendesk_ticket_id: '400944',
    zendesk_url: zd('400944'),
    productboard_note_id: null,
    productboard_url: null,
    productboard_status: 'Not Logged',
    pm_owner: 'None',
    pillar: 'Analytics',
    reporter: '',
    created_date: '2026-07-09',
    last_updated: '2026-07-09T00:00:00Z',
    notes: 'Channel: #pillar-query. Temp fix deployed, cache extended; concurrent PP queries limited.',
    engineering_ref: null,
  },
  {
    id: 20,
    topic: 'Data Table pruning warning shown on simple tables (misleading banner)',
    summary: 'The Data Table pruning warning shows on simple tables where no rows are pruned (misleading banner).',
    classification: 'Bug',
    fressnapf_status: 'Open',
    amplitude_status: 'On Hold',
    zendesk_ticket_id: null,
    zendesk_url: null,
    productboard_note_id: null,
    productboard_url: null,
    productboard_status: 'Not Logged',
    pm_owner: 'None',
    pillar: 'Analytics',
    reporter: '',
    created_date: '2026-07-09',
    last_updated: '2026-07-09T00:00:00Z',
    notes: 'Channel: #pillar-marketer-analytics. Deemed working as expected; treated as a UX improvement, not a bug.',
    engineering_ref: 'MAR-391',
  },
  {
    id: 21,
    topic: 'Partial rows shown in Data Table (investigation)',
    summary: 'Partial rows shown in a Data Table — under investigation.',
    classification: 'Bug',
    fressnapf_status: 'Open',
    amplitude_status: 'On Hold',
    zendesk_ticket_id: null,
    zendesk_url: null,
    productboard_note_id: null,
    productboard_url: null,
    productboard_status: 'Not Logged',
    pm_owner: 'None',
    pillar: 'Analytics',
    reporter: '',
    created_date: '2026-07-09',
    last_updated: '2026-07-09T00:00:00Z',
    notes: 'Channel: #pillar-marketer-analytics / #marketing-analytics. Recovered on its own; root-cause investigation requested.',
    engineering_ref: 'CAP-518',
  },
  {
    id: 22,
    topic: 'Group-by returns (none) for a combo that previously worked (possible regression)',
    summary: 'Group-by returns (none) for a metric+group-by combo that previously worked — possible regression.',
    classification: 'Bug',
    fressnapf_status: 'Fixed',
    amplitude_status: 'Closed',
    zendesk_ticket_id: null,
    zendesk_url: null,
    productboard_note_id: null,
    productboard_url: null,
    productboard_status: 'Not Logged',
    pm_owner: 'None',
    pillar: 'Analytics',
    reporter: '',
    created_date: '2026-07-09',
    last_updated: '2026-07-09T00:00:00Z',
    notes: 'Channel: #session-everywhere. Session ticket. Investigated; cache-related, resolved via a hybrid formula metric.',
    engineering_ref: null,
  },
  {
    id: 23,
    topic: 'Sessions in table do not add up (group-by higher than total)',
    summary: 'Sessions in a table do not add up — group-by higher than the total; two channels shown as "last property value".',
    classification: 'Bug',
    fressnapf_status: 'Open',
    amplitude_status: 'On Hold',
    zendesk_ticket_id: null,
    zendesk_url: null,
    productboard_note_id: null,
    productboard_url: null,
    productboard_status: 'Not Logged',
    pm_owner: 'None',
    pillar: 'Analytics',
    reporter: 'Guy Sharon',
    created_date: '2026-07-09',
    last_updated: '2026-07-09T00:00:00Z',
    notes: 'Channel: #session-everywhere. Raised from a Fressnapf call; later unsure it reproduced.',
    engineering_ref: null,
  },
  {
    id: 24,
    topic: 'Chart segment labels cannot be changed / show random group-by value',
    summary: 'Chart segment labels cannot be changed / show a random group-by value ("app; SEO" vs "app"); no custom label.',
    classification: 'Bug',
    fressnapf_status: 'Open',
    amplitude_status: 'In Engineering',
    zendesk_ticket_id: null,
    zendesk_url: null,
    productboard_note_id: null,
    productboard_url: null,
    productboard_status: 'Not Logged',
    pm_owner: 'None',
    pillar: 'Analytics',
    reporter: '',
    created_date: '2026-07-09',
    last_updated: '2026-07-09T00:00:00Z',
    notes: 'Channel: #pillar-analytics. Tracked in Glean/Linear. Logged; Core Analytics ticket created (bug vs FR TBD).',
    engineering_ref: null,
  },
  {
    id: 25,
    topic: 'Cart properties drilldown error — "Invalid cart properties used unexpectedly"',
    summary: 'Cart properties drilldown error — "Invalid cart properties used unexpectedly"; no undo/remove (must reload).',
    classification: 'Bug',
    fressnapf_status: 'Open',
    amplitude_status: 'On Hold',
    zendesk_ticket_id: null,
    zendesk_url: null,
    productboard_note_id: null,
    productboard_url: null,
    productboard_status: 'Not Logged',
    pm_owner: 'None',
    pillar: 'Analytics',
    reporter: 'Jiayi / Curtis',
    created_date: '2026-07-09',
    last_updated: '2026-07-09T00:00:00Z',
    notes: 'Channel: #analytics-persisted-properties-merchandising. Flagged possibly known; empty-state revert fix suggested.',
    engineering_ref: null,
  },
  {
    id: 26,
    topic: 'Pruning / "server too busy" message creating stakeholder friction (JL top priority)',
    summary: 'Pruning / "server too busy" message on screen creating stakeholder friction — Jose Luis top priority.',
    classification: 'Bug',
    fressnapf_status: 'Open',
    amplitude_status: 'In Engineering',
    zendesk_ticket_id: '401199',
    zendesk_url: zd('401199'),
    productboard_note_id: null,
    productboard_url: null,
    productboard_status: 'Not Logged',
    pm_owner: 'None',
    pillar: 'Analytics',
    reporter: '',
    created_date: '2026-07-09',
    last_updated: '2026-07-09T00:00:00Z',
    notes: 'Channel: #ZC Fressnapf channel. #399666 resolved; #401199 flagged top priority.',
    engineering_ref: null,
  },
]
